application: geek-accounting
version: 1
runtime: go
api_version: go1

handlers:
- url: /charts-of-accounts.*
  script: _go_app
  secure: always
- url: /ping
  script: _go_app
  secure: always
- url: /password
  script: _go_app
  secure: always
- url: /users.*
  script: _go_app
  secure: always
- url: /(.*\.html)$
  static_files: client/\1
  upload: client/.*\.html
- url: /css
  static_dir: client/css
- url: /js
  static_dir: client/js
- url: /partials
  static_dir: client/partials
- url: /
  static_files: client/index.html
  upload: client/index.html

inbound_services:
- warmup