application: geek-accounting
version: 1
runtime: go
api_version: go1

handlers:
- url: /charts-of-accounts.*
  script: _go_app
  secure: always
- url: /(.*\.html)$
  static_files: ../client/\1
  upload: /(.*\.html)$
- url: /js
  static_dir: ../client/js
- url: /
  static_files: ../client/index.html
  upload: ../client/index.html
